package server

import (
	"github.com/korotovsky/slack-mcp-server/pkg/handler"
	"github.com/korotovsky/slack-mcp-server/pkg/provider"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"go.uber.org/zap"
)

func registerCoreTools(s *server.MCPServer, provider *provider.ApiProvider, logger *zap.Logger, enabledTools []string) {
	conversationsHandler := handler.NewConversationsHandler(provider, logger)
	authStatusHandler := handler.NewAuthStatusHandler(provider, logger)

	addEnabledTool(s, enabledTools, ToolSlackAuthStatus, "", newDailyPowerTool(ToolSlackAuthStatus,
		mcp.WithDescription("Report Slack auth, cache readiness, and browser-session health. Use before activity or saved tools when auth may have expired."),
	), authStatusHandler.Handler)

	addEnabledTool(s, enabledTools, ToolConversationsOpen, "", mcp.NewTool(ToolConversationsOpen,
		mcp.WithDescription("Open a direct message (DM) or multi-person direct message (MPIM) with one or more users. Returns the channel ID of the opened conversation."),
		mcp.WithTitleAnnotation("Open Conversation"),
		mcp.WithString("users",
			mcp.Required(),
			mcp.Description("Comma-separated list of user IDs or @usernames to open a DM with. Example: U12345678, @username"),
		),
	), conversationsHandler.ConversationsOpenHandler)

	addEnabledTool(s, enabledTools, ToolConversationsHistory, "", mcp.NewTool(ToolConversationsHistory,
		mcp.WithDescription("Fetch messages from a channel or DM by channel_id. When more messages exist, the cursor value in the last CSV row is the 'cursor' parameter for the next call."),
		mcp.WithTitleAnnotation("Get Conversation History"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithBoolean("include_activity_messages",
			mcp.Description("If true, include activity messages such as 'channel_join' or 'channel_leave'. Default is false."),
			mcp.DefaultBool(false),
		),
		mcp.WithString("cursor",
			mcp.Description("Pagination cursor. Pass the cursor value from the last row of the previous response."),
		),
		mcp.WithString("limit",
			mcp.DefaultString("1d"),
			mcp.Description("How much history to fetch: a time range ('1d' for 1 day, '1w' for 1 week, '30d', '90d' which is the free-tier history limit) or a number of messages (e.g. 50). Default is 1d. Ignored when 'cursor' is set."),
		),
		mcp.WithString("detail",
			mcp.Description(toolDetailDescription),
			mcp.Enum("standard", "full"),
		),
	), conversationsHandler.ConversationsHistoryHandler)

	addEnabledTool(s, enabledTools, ToolConversationsReplies, "", mcp.NewTool(ToolConversationsReplies,
		mcp.WithDescription("Fetch a thread's messages by channel_id and thread_ts. When more messages exist, the cursor value in the last CSV row is the 'cursor' parameter for the next call."),
		mcp.WithTitleAnnotation("Get Thread Replies"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("thread_ts",
			mcp.Required(),
			mcp.Description("Timestamp of the thread's parent message, or of any message in the thread, in format 1234567890.123456."),
		),
		mcp.WithBoolean("include_activity_messages",
			mcp.Description("If true, include activity messages such as 'channel_join' or 'channel_leave'. Default is false."),
			mcp.DefaultBool(false),
		),
		mcp.WithString("cursor",
			mcp.Description("Pagination cursor. Pass the cursor value from the last row of the previous response."),
		),
		mcp.WithString("limit",
			mcp.DefaultString("1d"),
			mcp.Description("How many replies to fetch: a time range ('1d' for 1 day, '30d', '90d' which is the free-tier history limit) or a number of messages (e.g. 50). Default is 1d. Ignored when 'cursor' is set."),
		),
		mcp.WithString("detail",
			mcp.Description(toolDetailDescription),
			mcp.Enum("standard", "full"),
		),
	), conversationsHandler.ConversationsRepliesHandler)

	addEnabledTool(s, enabledTools, ToolReactionsGet, "", mcp.NewTool(ToolReactionsGet,
		mcp.WithDescription("Get detailed reaction data for a specific message, including which users reacted with each emoji. Returns CSV with Emoji, Count, and Users (semicolon-separated user IDs) columns."),
		mcp.WithTitleAnnotation("Get Message Reactions"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("timestamp",
			mcp.Required(),
			mcp.Description("Timestamp of the message to get reactions for, in format 1234567890.123456."),
		),
	), conversationsHandler.ReactionsGetHandler)

	addEnabledTool(s, enabledTools, ToolConversationsGetMessage, "", newDailyPowerTool(ToolConversationsGetMessage,
		mcp.WithDescription("Fetch a single message by channel and timestamp. Use the MsgID column from any compact CSV output as the timestamp, for example to re-fetch a message with detail: 'full' after an attachment-truncation receipt. Returns the same CSV format as conversations_history."),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("timestamp",
			mcp.Required(),
			mcp.Description("Timestamp of the message to fetch, in format 1234567890.123456."),
		),
		mcp.WithString("detail",
			mcp.Description(toolDetailDescription),
			mcp.Enum("standard", "full"),
		),
	), conversationsHandler.ConversationsGetMessageHandler)

	addEnabledTool(s, enabledTools, ToolConversationsAddMessage, "SLACK_MCP_ADD_MESSAGE_TOOL", mcp.NewTool(ToolConversationsAddMessage,
		mcp.WithDescription("Post a message to a channel or DM by channel_id. Pass thread_ts to reply in a thread."),
		mcp.WithTitleAnnotation("Send Message"),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("thread_ts",
			mcp.Description("Timestamp of an existing message, in format 1234567890.123456, identifying the thread to reply in. Omit to post to the channel itself."),
		),
		mcp.WithString("text",
			mcp.Description("Message text in specified content_type format. Example: 'Hello, world!' for text/plain or '# Hello, world!' for text/markdown."),
		),
		mcp.WithString("content_type",
			mcp.DefaultString("text/markdown"),
			mcp.Description("Content type of the message. Default is 'text/markdown'. Allowed values: 'text/markdown', 'text/plain'. Ignored when blocks is provided."),
		),
		mcp.WithString("blocks",
			mcp.Description("Raw Slack Block Kit JSON array for rich message formatting (rich_text lists, code blocks, etc.). When provided, this takes precedence over text/content_type for rendering. The text parameter becomes the notification fallback text."),
		),
	), conversationsHandler.ConversationsAddMessageHandler)

	addEnabledTool(s, enabledTools, ToolConversationsDraftMessage, "", mcp.NewTool(ToolConversationsDraftMessage,
		mcp.WithDescription("Preview a message without sending it. Returns the formatted message for review. Send it with conversations_add_message."),
		mcp.WithTitleAnnotation("Draft Message"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithDestructiveHintAnnotation(false),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("thread_ts",
			mcp.Description("Timestamp of an existing message, in format 1234567890.123456, identifying the thread the draft replies to. Omit to draft for the channel itself."),
		),
		mcp.WithString("text",
			mcp.Required(),
			mcp.Description("Message text in specified content_type format. Example: 'Hello, world!' for text/plain or '# Hello, world!' for text/markdown."),
		),
		mcp.WithString("content_type",
			mcp.DefaultString("text/markdown"),
			mcp.Description("Content type of the message. Default is 'text/markdown'. Allowed values: 'text/markdown', 'text/plain'."),
		),
	), conversationsHandler.ConversationsDraftMessageHandler)

	addEnabledTool(s, enabledTools, ToolReactionsAdd, "SLACK_MCP_REACTION_TOOL", mcp.NewTool(ToolReactionsAdd,
		mcp.WithDescription("Add an emoji reaction to a message."),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("timestamp",
			mcp.Required(),
			mcp.Description("Timestamp of the message to add reaction to, in format 1234567890.123456."),
		),
		mcp.WithString("emoji",
			mcp.Required(),
			mcp.Description("Emoji name without colons, e.g. 'thumbsup', 'heart', 'rocket'."),
		),
	), conversationsHandler.ReactionsAddHandler)

	addEnabledTool(s, enabledTools, ToolReactionsRemove, "SLACK_MCP_REACTION_TOOL", newDailyPowerTool(ToolReactionsRemove,
		mcp.WithDescription("Remove an emoji reaction from a message."),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @, e.g. #general or @username_dm."),
		),
		mcp.WithString("timestamp",
			mcp.Required(),
			mcp.Description("Timestamp of the message to remove reaction from, in format 1234567890.123456."),
		),
		mcp.WithString("emoji",
			mcp.Required(),
			mcp.Description("Emoji name without colons, e.g. 'thumbsup', 'heart', 'rocket'."),
		),
	), conversationsHandler.ReactionsRemoveHandler)

	addEnabledTool(s, enabledTools, ToolAttachmentGetData, "SLACK_MCP_ATTACHMENT_TOOL", mcp.NewTool(ToolAttachmentGetData,
		mcp.WithDescription("Download an attachment's content by file ID. Returns file metadata and content (text files as-is, binary files as base64). Maximum file size is 5MB."),
		mcp.WithTitleAnnotation("Get Attachment Data"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("file_id",
			mcp.Required(),
			mcp.Description("Attachment ID in format Fxxxxxxxxxx. The AttachmentIDs field of message metadata lists IDs with filenames when FileCount > 0."),
		),
	), conversationsHandler.FilesGetHandler)

	// Bot tokens cannot use search.messages.
	if !provider.IsBotToken() {
		addEnabledTool(s, enabledTools, ToolConversationsSearchMessages, "", mcp.NewTool(ToolConversationsSearchMessages,
			mcp.WithDescription("Search messages across channels and DMs. All filters are optional. If no filter is set, search_query is required."),
			mcp.WithTitleAnnotation("Search Messages"),
			mcp.WithReadOnlyHintAnnotation(true),
			mcp.WithString("search_query",
				mcp.Description("Search query, e.g. 'marketing report'. A full Slack message URL such as 'https://slack.com/archives/C1234567890/p1234567890123456' returns that single message and ignores all other parameters."),
			),
			mcp.WithString("filter_in_channel",
				mcp.Description("Limit search to one public or private channel by ID or name, e.g. 'C1234567890', 'G1234567890', or '#general'. Omit to search all channels."),
			),
			mcp.WithString("filter_in_im_or_mpim",
				mcp.Description("Limit search to one DM or multi-person DM by ID or name, e.g. 'D1234567890' or '@username_dm'. Omit to search all DMs and MPIMs."),
			),
			mcp.WithString("filter_users_with",
				mcp.Description("Only messages in threads and DMs with a specific user, by ID or display name, e.g. 'U1234567890' or '@username'. Omit to search all threads and DMs."),
			),
			mcp.WithString("filter_users_from",
				mcp.Description("Only messages sent by a specific user, by ID or display name, e.g. 'U1234567890' or '@username'. Omit to search all users."),
			),
			mcp.WithString("filter_date_before",
				mcp.Description("Only messages sent before a date. Accepts 'YYYY-MM-DD' (e.g. '2023-10-01'), 'July', 'Yesterday', or 'Today'."),
			),
			mcp.WithString("filter_date_after",
				mcp.Description("Only messages sent after a date. Accepts 'YYYY-MM-DD' (e.g. '2023-10-01'), 'July', 'Yesterday', or 'Today'."),
			),
			mcp.WithString("filter_date_on",
				mcp.Description("Only messages sent on a specific date. Accepts 'YYYY-MM-DD' (e.g. '2023-10-01'), 'July', 'Yesterday', or 'Today'."),
			),
			mcp.WithString("filter_date_during",
				mcp.Description("Only messages sent during a named period, e.g. 'July', 'Yesterday', or 'Today'."),
			),
			mcp.WithBoolean("filter_threads_only",
				mcp.Description("If true, return only messages from threads. Default is false."),
			),
			mcp.WithString("filter_has",
				mcp.Description("Only messages containing a given element: 'link', 'reaction', 'pin', 'file', or an emoji name like ':eyes:'. Maps to Slack's has: search modifier."),
			),
			mcp.WithString("cursor",
				mcp.DefaultString(""),
				mcp.Description("Pagination cursor. Pass the cursor value from the last row of the previous response."),
			),
			mcp.WithNumber("limit",
				mcp.DefaultNumber(100),
				mcp.Description("Maximum number of results, an integer between 1 and 100. Default is 100."),
			),
			mcp.WithString("sort",
				mcp.DefaultString("score"),
				mcp.Description("Sort order: 'score' (default, relevance) or 'timestamp' (most recent first)."),
			),
			mcp.WithString("detail",
				mcp.Description(toolDetailDescription),
				mcp.Enum("standard", "full"),
			),
		), conversationsHandler.ConversationsSearchHandler)
	}

	addEnabledTool(s, enabledTools, ToolUsersSearch, "", mcp.NewTool(ToolUsersSearch,
		mcp.WithDescription("Search for users by name, email, display name, or Slack user ID. If a Slack user ID is provided (e.g. U07VCEPP4N5), the user is looked up directly. Returns user details and DM channel ID if available."),
		mcp.WithTitleAnnotation("Search Users"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("query",
			mcp.Required(),
			mcp.Description("Search query. Matches against real name, display name, username, email, or a Slack user ID (e.g. U07VCEPP4N5)."),
		),
		mcp.WithNumber("limit",
			mcp.DefaultNumber(10),
			mcp.Description("Maximum number of results to return (1-100). Default is 10."),
		),
	), conversationsHandler.UsersSearchHandler)

	addEnabledTool(s, enabledTools, ToolFilesList, "SLACK_MCP_FILES_LIST_TOOL", mcp.NewTool(ToolFilesList,
		mcp.WithDescription("List files shared in a Slack channel or workspace. Returns file metadata including ID, name, type, size, uploader, and permalink. Pass a file ID from the results to attachment_get_data to download content. The cursor column of the last row paginates."),
		mcp.WithTitleAnnotation("List Files"),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Description("Filter files by channel ID (format Cxxxxxxxxxx) or channel name (e.g. #general). If omitted, lists files across all channels."),
		),
		mcp.WithString("user_id",
			mcp.Description("Filter files uploaded by a specific user ID (format Uxxxxxxxxxx)."),
		),
		mcp.WithString("types",
			mcp.DefaultString("all"),
			mcp.Description("Filter by file type. Comma-separated values: all, spaces, snippets, images, gdocs, zips, pdfs. Default is all."),
		),
		mcp.WithString("limit",
			mcp.DefaultString("50"),
			mcp.Description("Maximum number of files to return (1-200). Default is 50."),
		),
		mcp.WithString("cursor",
			mcp.Description("Pagination cursor. Pass the cursor value from the last row of the previous response."),
		),
	), conversationsHandler.FilesListHandler)

	addEnabledTool(s, enabledTools, ToolConversationsMark, "SLACK_MCP_MARK_TOOL", newDailyPowerTool(ToolConversationsMark,
		mcp.WithDescription("Mark a channel or DM as read. If no timestamp is provided, marks all messages as read."),
		mcp.WithTitleAnnotation("Mark as Read"),
		mcp.WithDestructiveHintAnnotation(false),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @ (e.g. #general, @username)."),
		),
		mcp.WithString("ts",
			mcp.Description("Timestamp of the message to mark as read up to. If not provided, marks all messages as read."),
		),
	), conversationsHandler.ConversationsMarkHandler)

	addEnabledTool(s, enabledTools, ToolConversationsLeave, "SLACK_MCP_CHANNEL_MEMBERSHIP_TOOL", mcp.NewTool(ToolConversationsLeave,
		mcp.WithDescription("Leave a channel, group conversation, or DM. Cannot leave the #general channel."),
		mcp.WithTitleAnnotation("Leave Channel"),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel or DM name starting with # or @ (e.g. #general, @username)."),
		),
	), conversationsHandler.ConversationsLeaveHandler)

	addEnabledTool(s, enabledTools, ToolConversationsJoin, "SLACK_MCP_CHANNEL_MEMBERSHIP_TOOL", mcp.NewTool(ToolConversationsJoin,
		mcp.WithDescription("Join a public channel. Use channels_list or channels_me to find channel IDs."),
		mcp.WithTitleAnnotation("Join Channel"),
		mcp.WithIdempotentHintAnnotation(true),
		mcp.WithString("channel_id",
			mcp.Required(),
			mcp.Description("Channel ID in format Cxxxxxxxxxx, or a channel name starting with # (e.g. #general)."),
		),
	), conversationsHandler.ConversationsJoinHandler)

	usergroupsHandler := handler.NewUsergroupsHandler(provider, logger)

	addEnabledTool(s, enabledTools, ToolUsergroupsList, "", newDailyPowerTool(ToolUsergroupsList,
		mcp.WithDescription("List all user groups (subteams) in the workspace. User groups are mention handles like @engineering that notify all members. Use this to find a group's ID before joining or updating it. Returns CSV with columns: id, name, handle, description, user_count, is_external, date_create, date_update; when include_users=true also users (semicolon-separated user IDs)."),
		mcp.WithBoolean("include_users",
			mcp.Description("Include semicolon-separated user IDs in the users CSV column. Default is false."),
			mcp.DefaultBool(false),
		),
		mcp.WithBoolean("include_count",
			mcp.Description("Include user count for each group. Default is true."),
			mcp.DefaultBool(true),
		),
		mcp.WithBoolean("include_disabled",
			mcp.Description("Include disabled/archived groups. Default is false."),
			mcp.DefaultBool(false),
		),
	), usergroupsHandler.UsergroupsListHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsMe, "", mcp.NewTool(ToolUsergroupsMe,
		mcp.WithDescription("Manage your own user group membership. action='list' shows the groups you belong to, 'join' adds you to a group, 'leave' removes you. Unlike usergroups_users_update, this needs no full member list."),
		mcp.WithTitleAnnotation("My User Groups"),
		mcp.WithString("action",
			mcp.Required(),
			mcp.Description("Action to perform: 'list' returns CSV of groups you're a member of, 'join' adds you to a group, 'leave' removes you from a group."),
		),
		mcp.WithString("usergroup_id",
			mcp.Description("ID of the user group (starts with 'S', e.g., 'S0123456789'). Required for 'join' and 'leave' actions. Get IDs from usergroups_list."),
		),
	), usergroupsHandler.UsergroupsMeHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsMine, "", newDailyPowerTool(ToolUsergroupsMine,
		mcp.WithDescription("List the user groups the authenticated Slack user belongs to."),
	), usergroupsHandler.UsergroupsMineHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsJoin, "SLACK_MCP_USERGROUPS_WRITE_TOOL", newDailyPowerTool(ToolUsergroupsJoin,
		mcp.WithDescription("Add the authenticated Slack user to one user group. Requires client confirmation."),
		mcp.WithString("usergroup_id", mcp.Required(), mcp.Description("User group ID beginning with S.")),
	), usergroupsHandler.UsergroupsJoinHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsLeave, "SLACK_MCP_USERGROUPS_WRITE_TOOL", newDailyPowerTool(ToolUsergroupsLeave,
		mcp.WithDescription("Remove the authenticated Slack user from one user group. Requires client confirmation."),
		mcp.WithString("usergroup_id", mcp.Required(), mcp.Description("User group ID beginning with S.")),
	), usergroupsHandler.UsergroupsLeaveHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsCreate, "SLACK_MCP_USERGROUPS_WRITE_TOOL", newDailyPowerTool(ToolUsergroupsCreate,
		mcp.WithDescription("Create a new user group (mention group) in the Slack workspace. After creation, use usergroups_users_update to add members, or users can join themselves with usergroups_me. The handle becomes the @mention (e.g., handle='engineering' creates @engineering)."),
		mcp.WithTitleAnnotation("Create User Group"),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("name",
			mcp.Required(),
			mcp.Description("Display name of the user group (e.g., 'Engineering Team', 'Design Squad')."),
		),
		mcp.WithString("handle",
			mcp.Description("The @mention handle without the @ symbol (e.g., 'engineering' for @engineering). Keep it short and lowercase. If omitted, Slack auto-generates one from the name."),
		),
		mcp.WithString("description",
			mcp.Description("Purpose or description shown in group details (e.g., 'Backend and frontend engineers')."),
		),
		mcp.WithString("channels",
			mcp.Description("Comma-separated channel IDs where this group is commonly mentioned. Members get suggestions to join these channels."),
		),
	), usergroupsHandler.UsergroupsCreateHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsUpdate, "SLACK_MCP_USERGROUPS_WRITE_TOOL", newDailyPowerTool(ToolUsergroupsUpdate,
		mcp.WithDescription("Update a user group's metadata: name, handle (@mention), description, or default channels. Does NOT change members, use usergroups_users_update for that. At least one field must be provided."),
		mcp.WithTitleAnnotation("Update User Group"),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("usergroup_id",
			mcp.Required(),
			mcp.Description("ID of the user group to update (starts with 'S', e.g., 'S0123456789'). Get IDs from usergroups_list."),
		),
		mcp.WithString("name",
			mcp.Description("New display name for the group."),
		),
		mcp.WithString("handle",
			mcp.Description("New @mention handle (without @). Changing this changes how users mention the group."),
		),
		mcp.WithString("description",
			mcp.Description("New description for the group."),
		),
		mcp.WithString("channels",
			mcp.Description("New default channel IDs (comma-separated). Replaces existing default channels."),
		),
	), usergroupsHandler.UsergroupsUpdateHandler)

	addEnabledTool(s, enabledTools, ToolUsergroupsUsersUpdate, "SLACK_MCP_USERGROUPS_WRITE_TOOL", newDailyPowerTool(ToolUsergroupsUsersUpdate,
		mcp.WithDescription("Replace all members of a user group with a new list. WARNING: any user not in the 'users' parameter is removed. To add or remove only yourself, use usergroups_me instead. To add one user without removing others, first get current members from usergroups_list with include_users=true, then call this with the combined list."),
		mcp.WithTitleAnnotation("Update User Group Members"),
		mcp.WithDestructiveHintAnnotation(true),
		mcp.WithString("usergroup_id",
			mcp.Required(),
			mcp.Description("ID of the user group (starts with 'S', e.g., 'S0123456789'). Get IDs from usergroups_list."),
		),
		mcp.WithString("users",
			mcp.Required(),
			mcp.Description("Comma-separated user IDs forming the COMPLETE new member list (e.g., 'U0123456789,U9876543210'). Current members not in this list are removed."),
		),
	), usergroupsHandler.UsergroupsUsersUpdateHandler)

	browserSession := provider.ConfiguredWithBrowserSession()
	addSavedList := browserSession && shouldAddTool(ToolSavedList, enabledTools, "")
	addSavedUpdate := browserSession && shouldAddTool(ToolSavedUpdate, enabledTools, "SLACK_MCP_SAVED_WRITE_TOOL")
	addSavedClear := browserSession && shouldAddTool(ToolSavedClearCompleted, enabledTools, "SLACK_MCP_SAVED_WRITE_TOOL")
	if addSavedList || addSavedUpdate || addSavedClear {
		savedHandler := handler.NewSavedHandler(provider, logger, conversationsHandler)
		if addSavedList {
			s.AddTool(newDailyPowerTool(ToolSavedList,
				mcp.WithDescription("List saved items from Slack's 'Save for Later' panel. Returns items the user has saved, with optional message content. Replaces the deprecated stars.list API. Requires browser session tokens (xoxc/xoxd)."),
				mcp.WithString("filter",
					mcp.Description("Filter saved items: 'saved' (active/in-progress, default), 'completed' (marked done), 'archived'."),
					mcp.DefaultString("saved"),
				),
				mcp.WithNumber("limit",
					mcp.Description("Maximum number of items to return from this page. Default is 50."),
					mcp.DefaultNumber(50),
				),
				mcp.WithString("cursor",
					mcp.Description("Pagination cursor from meta.next_cursor in the previous response."),
				),
				mcp.WithBoolean("include_messages",
					mcp.Description("If true (default), fetches the actual saved message content. If false, returns metadata only."),
					mcp.DefaultBool(true),
				),
				mcp.WithNumber("max_messages_per_item",
					mcp.Description("Max messages to fetch per saved item (for thread replies). Default is 5."),
					mcp.DefaultNumber(5),
				),
				mcp.WithString("detail",
					mcp.Description(toolDetailDescription),
					mcp.Enum("standard", "full"),
				),
			), savedHandler.SavedListHandler)
		}

		if addSavedUpdate {
			s.AddTool(newDailyPowerTool(ToolSavedUpdate,
				mcp.WithDescription("Update a saved item: mark as completed, set a due date, or both. Use item_id and ts values from saved_list output. Replaces the deprecated stars.add/stars.remove APIs."),
				mcp.WithTitleAnnotation("Update Saved Item"),
				mcp.WithDestructiveHintAnnotation(true),
				mcp.WithString("item_id",
					mcp.Required(),
					mcp.Description("Channel/DM ID where the saved message lives (from saved_list output)."),
				),
				mcp.WithString("ts",
					mcp.Required(),
					mcp.Description("Message timestamp of the saved item (from saved_list output)."),
				),
				mcp.WithString("mark",
					mcp.Description("Set to 'completed' to mark the item as done."),
				),
				mcp.WithNumber("date_due",
					mcp.Description("Unix timestamp for due date/reminder. Set to 0 to clear."),
				),
			), savedHandler.SavedUpdateHandler)
		}

		if addSavedClear {
			s.AddTool(newDailyPowerTool(ToolSavedClearCompleted,
				mcp.WithDescription("Clear all completed saved items from the 'Save for Later' panel. This is a bulk operation that removes all items with state='completed'."),
				mcp.WithTitleAnnotation("Clear Completed Saved Items"),
				mcp.WithDestructiveHintAnnotation(true),
			), savedHandler.SavedClearCompletedHandler)
		}
	}
}
